zuul:
  routes:
    provider: /uuu/**
  ignored-patterns:
    - /provider/**/
  sensitive-headers:
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 192.168.1.195
    port: 5672
    username: guest
    password: guest
